### ISSUE TITLE
Secrets files not found

### ISSUE THREAD

**Issue by seryeb** [withinboredom/scalable-wordpress#1]
Hi, very good job!!!
When I execute the script I get:
`bash -x swarm/turn-up.sh superblog`
> + namespace=superblog
> + '[' superblog == '' ']'
> + dockerDeploy secrets
> + docker stack deploy -c swarm/secrets.yml superblog
> open .secrets/SECURE_AUTH_KEY: no such file or directory

Must I create the secret files before executes the script??

Thanks in advance

**Comment by seryeb** [comment]
Previously I must execute init.sh...

**Comment by PiperMp3** [comment]
Hey how exactly did you do this?
I got this as well, ran init.sh and secrets were created.

However the turn-up script still complaints the secrets does not exists but are referencing the correct path.

Does the secrets have to be a specific permission?

**Comment by PiperMp3** [comment]
open /xxxxxxxx/scalable-wordpress/swarm/.secrets/NONCE_SALT: no such file or directory
Creating network blog_default
service seed: undefined secret "xtrabackup_password"
Just gets stuck on the different secrets not existing + "undefined secret" on xtrabackup.

Does not progress.
Quite sure this kit is outdated at this point?

**Comment by PiperMp3** [comment]
/.secrets# ls 
AUTH_KEY   LOGGED_IN_KEY   NONCE_KEY   SECURE_AUTH_KEY   mysql_password       xtrabackup_password
AUTH_SALT  LOGGED_IN_SALT  NONCE_SALT  SECURE_AUTH_SALT  mysql_root_password

**Comment by withinboredom** [comment]
> Quite sure this kit is outdated at this point?

It's been since 2017 since I've last updated it, it's quite likely the secrets API's have changed. It probably doesn't need much to update it, but I don't have the time to. There used to be a few sites running on this, but now they use something loosely based on it. Docker swarm seems like it's mostly dead, so I haven't felt the need to update this.
